name: CI Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: List files
        run: ls -la

      - name: Restore dependencies
        run: dotnet restore
        continue-on-error: true

      - name: Build
        run: dotnet build --no-restore --configuration Release
        if: success()

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release
        if: success()

      - name: Custom script
        run: |
          echo "Running custom script"
          ./scripts/custom_script.sh
        if: success()
